server:
  port: 9000
spring:
  profiles:
    include: driver,toolkit
kaptcha:
  height: 50
  width: 200
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1
jwt:
  route:
    authentication:
      path: /auth
  header: Authorization
  expiration: 604800
  secret: almighty.hanhuide.project
  startsWith: "Bearer "
  token:
    validTime:
